// da-selector/react/container/demo-app.js
import React, { Component } from 'react'
import './page-override.css'

import DaSelector from '../component/da-selector'

class DemoApp extends Component {
  constructor(props) {
    super(props)

    this.state = {
      selectOption: {},
    }
  }

  render() {
    return (
      <div>
        <p>Your choice is: <span>{this.state.selectOption.display}</span></p>
        <DaSelector
          id="demo-selector"
          optionDataList={this.getRandomData(20)}
          placeholder="This is yield name"
          onChange={(newOption, oldOption) => {
            this.setState({
              selectOption: newOption,
            })
          }}
        />
      </div>
    )
  }

  getRandomData(length) {
    let result = []
      , i

    result.push({
      id: 'id-0',
      display: 'Please select an option',
    })

    for (i = 1; i < length; i++) {
      result.push({
        id: `id-${i}`,
        display: `${i} - ${Math.random().toString(16).slice(2)}`,
      })
    }

    return result
  }
}

export default DemoApp

// vue/component/demo-app.vue
<template lang="pug">
  div
    p
      | Your choice is:
      span {{ selectedOptionData.display }}
    da-selector(
      id="demo-selector"
      placeholder="This is yield name"
      :optionDataList="optionDataList"
      :onChange="onChange"
    )
</template>

<script>
  import DaSelector from './da-selector.vue'

  export default {
    components: { DaSelector },
    data() {
      const optionDataList = getRandomData(20)
      return {
        optionDataList,
        selectedOptionData: optionDataList[0],
      }
    },
    methods: {
      onChange(newOption, oldOption) {
        this.selectedOptionData = newOption
      },
    },
  }

  function getRandomData(length) {
    let result = []
      , i

    result.push({
      id: 'id-0',
      display: 'Please select an option',
    })

    for (i = 1; i < length; i++) {
      result.push({
        id: `id-${i}`,
        display: `${i} - ${Math.random().toString(16).slice(2)}`,
      })
    }

    return result
  }
</script>

<style src="../shared/reset.css"></style>
<style src="./demo-app.css"></style>
