// vue/component/demo-app.vue
<template lang="pug">
  div
    p
      | Your choice is:
      span#user-choice {{ selectOption.display }}
    da-selector(
      id="demo-selector"
      name="input name"
      placeholder="input placeholder"
      :optionDataList="optionDataList"
      :onChange="onChange"
    )
</template>

<script>
  import DaSelector from './da-selector.vue'

  export default {
    components: { DaSelector },
    data() {
      const optionDataList = getRandomData(20)
      return {
        optionDataList,
        selectOption: {},
      }
    },
    methods: {
      onChange(newOption, oldOption) {
        this.selectOption = newOption
      },
    },
  }

  function getRandomData(length) {
    const result = [{
      id: '',
      display: 'Please select an option',
    }]

    for (let i = 1; i < length; i++) {
      result.push({
        id: `id-${i}`,
        display: `${i} - ${Math.random().toString(16).slice(2)}`,
      })
    }

    return result
  }
</script>

<style src="../shared/reset.css"></style>
<style src="./demo-app.css"></style>

// react-no-webpack/container/demo-app.js
import React, { Component } from 'react'
import './page-override.css'

import DaSelector from '../component/da-selector'

class DemoApp extends Component {
  constructor(props) {
    super(props)

    const optionDataList = this.getRandomData(20)
    this.state = {
      optionDataList,
      selectOption: optionDataList[0],
    }
  }

  shouldComponentUpdate(nextProps, nextState) {
    // to avoid `this.state.optionDataList` get random every time
    return this.state.selectOption != nextState.selectOption
  }

  render() {
    return (
      <div>
        <p>Your choice is:
          <span id="user-choice">{this.state.selectOption.display}</span>
        </p>
        <DaSelector
          id="demo-selector"
          name="input name"
          placeholder="input placeholder"
          optionDataList={this.state.optionDataList}
          onChange={(newOption, oldOption) => {
            this.setState({
              selectOption: newOption,
            })
          }}
        />
      </div>
    )
  }

  getRandomData(length) {
    const result = [{
      id: '',
      display: 'Please select an option',
    }]

    for (let i = 1; i < length; i++) {
      result.push({
        id: `id-${i}`,
        display: `${i} - ${Math.random().toString(16).slice(2)}`,
      })
    }

    return result
  }
}

export default DemoApp
